# Tony O'Donoghue
# July 2016
#
# server.R
#
# Linear Regression Application

library(shiny)
library(shinyjs)
library(corrplot)


#Limit number of row and col 
checkLimit <- function(val, maxval) {
    if (val>maxval) {
        val<-maxval
    }
    if (val<2) {
        val<-2
    }
    return(val)
}

# Autoploulate Dropdown for independent and dependent variables.
setDropdowns <- function(filedata,outputCtrl) {
    if (is.data.frame(filedata)) {
        uploadedData <-filedata
    }
    else {
        uploadedData <- filedata()
    }
    
    if (is.null(uploadedData)) return(NULL)
    items=names(uploadedData)
    names(items)=items
    
    outputCtrl$independent_input <- renderUI({
    selectInput("independent_input","Select ONE or MANY independent/input variables from:",items,multiple=TRUE)
    })
    
    outputCtrl$dependent_output <- renderUI({
        selectInput("dependent_output","Select ONE variable as dependent/output variable from:",items)
    })
}

# Show size of data
showRowCol <- function(data, outputCtrl){
    outputCtrl$out_rowscols <- renderText(paste("Data Table - Number of rows is: ", nrow(data), ". Number of columns is: ", ncol(data), "."))
}



shinyServer(function(input, output,session) {
    
    #Common Data Store#
    values <- reactiveValues(dfData = NULL, upFileName=NULL)
    
    # On File Upload button click load file data #
    observeEvent(input$file1, {
        uploadedData <- filedata()
        
        if (is.null(uploadedData)) {
            output$out_rowscols <- renderText(paste("No file loaded."))
            return(NULL)  
        }
        
        hide("lmsummary")
        hide("corPlot")
        showRowCol(uploadedData, output)
        setDropdowns(filedata, output)
        
        #na data set to 0
        uploadedData[is.na(uploadedData)]<-0
        output$contents <- renderTable({uploadedData}, caption = paste0("Uploaded File Data:", values$upFileName), caption.placement = getOption("xtable.caption.placement", "top"))
        values$dfData <- uploadedData
    })
    
    # File Uploaded Event #
    filedata <- reactive({
        infile <- input$file1

        if (is.null(infile)){
            return(NULL)
        }
        countF <- checkLimit(count.fields(infile$datapath,sep=input$sep),input$maxCols)
        countR <- checkLimit(input$maxRows,1000)
        
        values$upFileName<-infile$name

        f<- read.csv(infile$datapath, header=input$header, sep=input$sep,
                 			  nrows=countR )
        
        f[,1:countF]
    })

  
  # Generate Random Data Buttob click #
  observeEvent(input$btnGenerate, {

      if (input$btnGenerate >0) {
          
          session$sendCustomMessage(type = "resetFileInputHandler", 'file1')

          countF <- checkLimit(input$maxCols,20)
          countR <- checkLimit(input$maxRows,1000)
          df<-data.frame(replicate(countF,sample(1:80,countR,rep=TRUE)))
          df<-row(df)/100 + df #/*add a bit of linearity*/
          cnt <- countF-1
          names(df) <-c("Y",paste0('X',as.character(seq(1:cnt))))
          
          hide("corPlot")
          hide("lmsummary")
          setDropdowns(df, output)
          showRowCol(df, output)
          
          #na data is set to 0
          df[is.na(df)]<-0
          values$dfData <- df
          output$contents <- renderTable({df}, caption = "Autogenerated Random Data:",  caption.placement = getOption("xtable.caption.placement", "top"))

      }

  })
  
  # Linear Model Data Button click #
  observeEvent(input$btnLm, {
      
      if (input$btnLm >0) { 
         
          if (is.null(input$independent_input)) {
              show("lmsummary")
              output$lmsummary <- renderPrint({"Please select at least one input"})
              return(NULL)
          }
          
          if (is.null(values$dfData)) {
              return(NULL)
          }

          myFormula <- as.formula(paste(input$dependent_output," ~ ",paste(input$independent_input,collapse="+")))

          myResults <- summary(lm(myFormula ,data=values$dfData))
          output$lmsummary <- renderPrint({myResults})
          
          show("lmsummary")
          show("corPlot")
          output$corPlot <- renderPlot({corrplot(cor(values$dfData), order = "hclust", title="Correlation Between All Variables", mar=c(1,1,1,1))})
      }
  })
  
  
  output$out_rowscols <- renderText(paste("*No File loaded* Number of rows is: ", 0, ". Number of columns is: ", 0, "."))

})
